theme = "awesome-identity"
baseURL = "https://james-knott.github.io"
title = "James Knott"


## Profile Configurations
[params.profile]
  portrait = "/images/image1.png"
  firstname = "James"
  lastname = "Knott"
  title = "DevOps Engineer"
  bio = """James Knott brings over 20 years experience in IT as Systems Engineer, Network Architect, DBA, Security Engineer, DevOps Engineer

  """


## Footer Configurations
[params.footer]
  copyright = "© 2019 James Knott. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true


## Contacts Configurations
[params.contacts]
  email = "pythonboto3cookbook@gmail.com"
  github = "james-knott"
  twitter = "james.knott"
  facebook = "james.knott"
  linkedin = "buildmystartup"
  instagram = "james.knott"
  stackoverflow = "7919458"
  keybase = "james.knott"
  medium = "james.knott"
  youtube = "pythonboto3cookbook"




